# This file was generated by Spago2Nix

{ pkgs ? import <nixpkgs> {} }:

let
  inputs = {

    "arrays" = pkgs.stdenv.mkDerivation {
        name = "arrays";
        version = "cce2d13db0877d208a0cdc57c0e12d60e2b02cfb";
        src = pkgs.fetchgit {
          url = "https://github.com/purenix-org/purescript-arrays.git";
          rev = "cce2d13db0877d208a0cdc57c0e12d60e2b02cfb";
          sha256 = "1wwii10iz4ji7d9i216clb544343xpkgr1cl4vlnkijliwvfskjm";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "bifunctors" = pkgs.stdenv.mkDerivation {
        name = "bifunctors";
        version = "e2f1d603125a5f42338c6fae10422508be91eda6";
        src = pkgs.fetchgit {
          url = "https://github.com/purenix-org/purescript-bifunctors.git";
          rev = "e2f1d603125a5f42338c6fae10422508be91eda6";
          sha256 = "0fpprk875zh631pz5vfiqpdvm3jkb8w3hcsz058jwvijl1cng579";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "const" = pkgs.stdenv.mkDerivation {
        name = "const";
        version = "2a3730d452fa1d579642f2d7322a92ffc26f8ca1";
        src = pkgs.fetchgit {
          url = "https://github.com/purenix-org/purescript-const.git";
          rev = "2a3730d452fa1d579642f2d7322a92ffc26f8ca1";
          sha256 = "0ih9xn803bx0j3kvadvir62mfvzkdcw6gl65xbwqhbjcfh08zxk2";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "contravariant" = pkgs.stdenv.mkDerivation {
        name = "contravariant";
        version = "f131d673128a490d27f85039dea34b5b316cc16e";
        src = pkgs.fetchgit {
          url = "https://github.com/purenix-org/purescript-contravariant.git";
          rev = "f131d673128a490d27f85039dea34b5b316cc16e";
          sha256 = "13v63m5iwj4cjib7csl3v6ppnhp3y0w42shwjiikavivaj4pb8mc";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "control" = pkgs.stdenv.mkDerivation {
        name = "control";
        version = "14103f74386a315f159f85720fac0242810d5b38";
        src = pkgs.fetchgit {
          url = "https://github.com/purenix-org/purescript-control.git";
          rev = "14103f74386a315f159f85720fac0242810d5b38";
          sha256 = "1mg862bid36n80q037wd2pw9plh7p3fs8kcgmwkiipqdhr0zm52a";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "distributive" = pkgs.stdenv.mkDerivation {
        name = "distributive";
        version = "f6dcb7c7870a74c429376ce46a5ac25392b0f25c";
        src = pkgs.fetchgit {
          url = "https://github.com/purenix-org/purescript-distributive.git";
          rev = "f6dcb7c7870a74c429376ce46a5ac25392b0f25c";
          sha256 = "12gz85g0m0xnx67gfds4a8hc6hflj2qm8lj8yjwbr7wbnwyvxkzc";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "effect" = pkgs.stdenv.mkDerivation {
        name = "effect";
        version = "0f983fdcb6d45f09c823b1a8e44637b51829e7d5";
        src = pkgs.fetchgit {
          url = "https://github.com/thought2/purescript-effect.git";
          rev = "0f983fdcb6d45f09c823b1a8e44637b51829e7d5";
          sha256 = "12xhazk8y7ba9xzhn8cyc1cq2ab7ambjk4bfshvw299w31q3b7sm";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "either" = pkgs.stdenv.mkDerivation {
        name = "either";
        version = "3169946c381a961c8ccbfa078748cc4a87c80766";
        src = pkgs.fetchgit {
          url = "https://github.com/purenix-org/purescript-either.git";
          rev = "3169946c381a961c8ccbfa078748cc4a87c80766";
          sha256 = "1dbcj8579ac191fkv85615ahpzqaqk8gsdw6z114ilxaz8n7xjc3";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "exists" = pkgs.stdenv.mkDerivation {
        name = "exists";
        version = "0d5dbf6ba8b4cfdcc3fa514f429ffd645f9a078f";
        src = pkgs.fetchgit {
          url = "https://github.com/purenix-org/purescript-exists.git";
          rev = "0d5dbf6ba8b4cfdcc3fa514f429ffd645f9a078f";
          sha256 = "0mhqm67jkk485k6ivw6rf8dkaf4pql4r1kiaz2k9d8hvr0vkiv1r";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "foldable-traversable" = pkgs.stdenv.mkDerivation {
        name = "foldable-traversable";
        version = "bbb02b2752b1f1520c7c0b9f79bf7152002e989a";
        src = pkgs.fetchgit {
          url = "https://github.com/purenix-org/purescript-foldable-traversable.git";
          rev = "bbb02b2752b1f1520c7c0b9f79bf7152002e989a";
          sha256 = "0js08ysynb03lswnv5p5851dsr1rgyqgk4spp37a2l816smkzk0j";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "foreign" = pkgs.stdenv.mkDerivation {
        name = "foreign";
        version = "895901ad15d0c1517052a7a318b77c11cba72692";
        src = pkgs.fetchgit {
          url = "https://github.com/thought2/purescript-foreign.git";
          rev = "895901ad15d0c1517052a7a318b77c11cba72692";
          sha256 = "09s7r79yj8jpyc0a4kbniliqa109i6ac1yziwgfpbfsfhkwsy935";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "foreign-object" = pkgs.stdenv.mkDerivation {
        name = "foreign-object";
        version = "63de9f4e97b643dcfbe65da4dacf20d5303f6c6a";
        src = pkgs.fetchgit {
          url = "https://github.com/thought2/purescript-foreign-object.git";
          rev = "63de9f4e97b643dcfbe65da4dacf20d5303f6c6a";
          sha256 = "0mqm4f4cmrc4gx8vhhkys1d14bdmbkcp1qzs37dn7crivq61pv5g";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "foreign-path" = pkgs.stdenv.mkDerivation {
        name = "foreign-path";
        version = "fe7f41b7749955ee6acdc3edcdc448b48f788ecd";
        src = pkgs.fetchgit {
          url = "https://github.com/thought2/purescript-foreign-path.git";
          rev = "fe7f41b7749955ee6acdc3edcdc448b48f788ecd";
          sha256 = "0czaa1m53msxqh33ign0bzipixy0y06y19n20h8icmfvj7b6cpy5";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "functors" = pkgs.stdenv.mkDerivation {
        name = "functors";
        version = "5d67eb8f277da9ed2e22ba9e1b6fdd0ba00dfe3e";
        src = pkgs.fetchgit {
          url = "https://github.com/purenix-org/purescript-functors.git";
          rev = "5d67eb8f277da9ed2e22ba9e1b6fdd0ba00dfe3e";
          sha256 = "17gg6mf3p9x7s8j9zzrb48aq08lqwalpas76lmyyf60lw5b345ap";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "identity" = pkgs.stdenv.mkDerivation {
        name = "identity";
        version = "cb1f4df0bcd835bff8148881a64f4b136a5827d3";
        src = pkgs.fetchgit {
          url = "https://github.com/purenix-org/purescript-identity.git";
          rev = "cb1f4df0bcd835bff8148881a64f4b136a5827d3";
          sha256 = "1fiwxlz8swifjmyzmmnccfgsg5nrwaf6aqhcm4b1mnafrpzxwba0";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "invariant" = pkgs.stdenv.mkDerivation {
        name = "invariant";
        version = "30a5b24011c13d01d64337a459d0a7de68b93351";
        src = pkgs.fetchgit {
          url = "https://github.com/purenix-org/purescript-invariant.git";
          rev = "30a5b24011c13d01d64337a459d0a7de68b93351";
          sha256 = "02sbs6w67n2jqyfgjcvf3n4g3bh1yk265zx2r6djavifwznkzs6w";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "maybe" = pkgs.stdenv.mkDerivation {
        name = "maybe";
        version = "b13eab54d7e3b67c1820ea76e05181d34c42ee0d";
        src = pkgs.fetchgit {
          url = "https://github.com/purenix-org/purescript-maybe.git";
          rev = "b13eab54d7e3b67c1820ea76e05181d34c42ee0d";
          sha256 = "1ww15s7kfcwxvj3imqnwhsr95hfwsa68i415xigrgybscx1sgwgc";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "miraculix-lite" = pkgs.stdenv.mkDerivation {
        name = "miraculix-lite";
        version = "9b3a8ced22c78fe0e8ea1cd7352df5f5dae1dfbd";
        src = pkgs.fetchgit {
          url = "https://github.com/thought2/purescript-miraculix.git";
          rev = "9b3a8ced22c78fe0e8ea1cd7352df5f5dae1dfbd";
          sha256 = "0mlrhn39mf1hzsa64z3y64xmlj5hfalbd9bxjfkf8lxblz0wmvcq";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "newtype" = pkgs.stdenv.mkDerivation {
        name = "newtype";
        version = "13c4e4c8bd95a86aa7f04e6418efaf83d696cadc";
        src = pkgs.fetchgit {
          url = "https://github.com/purenix-org/purescript-newtype.git";
          rev = "13c4e4c8bd95a86aa7f04e6418efaf83d696cadc";
          sha256 = "1qwr1bchx67jrwgd6x4169k2bn6x35z4bpcbcczbws3im44i2yy8";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "nonempty" = pkgs.stdenv.mkDerivation {
        name = "nonempty";
        version = "467f1cf3810b9697b6a69ed5db3d4631e044c876";
        src = pkgs.fetchgit {
          url = "https://github.com/purenix-org/purescript-nonempty.git";
          rev = "467f1cf3810b9697b6a69ed5db3d4631e044c876";
          sha256 = "05zyva7p0xnczzg1gr75fw9yw2j8vnfnhkd1n1g9q2x1vrndirfs";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "orders" = pkgs.stdenv.mkDerivation {
        name = "orders";
        version = "757ab6d323dd5a2252c4198c65a821a92484751b";
        src = pkgs.fetchgit {
          url = "https://github.com/purenix-org/purescript-orders.git";
          rev = "757ab6d323dd5a2252c4198c65a821a92484751b";
          sha256 = "0780cbyafdvd7lwn90hp4y0g13wh8hvgw15bzlw57kaasz7hywla";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "partial" = pkgs.stdenv.mkDerivation {
        name = "partial";
        version = "948fdc982a3677fc4daa1b884e333d503b5dbac0";
        src = pkgs.fetchgit {
          url = "https://github.com/purenix-org/purescript-partial.git";
          rev = "948fdc982a3677fc4daa1b884e333d503b5dbac0";
          sha256 = "1i5vdk50majlwf1jfw32finv0x5ddqx749hr64lw89qlgnfkl26z";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "prelude" = pkgs.stdenv.mkDerivation {
        name = "prelude";
        version = "0a991d6422d5d57650955fab8468f7af82dba944";
        src = pkgs.fetchgit {
          url = "https://github.com/purenix-org/purescript-prelude.git";
          rev = "0a991d6422d5d57650955fab8468f7af82dba944";
          sha256 = "1fgnp9hsj512jf1f3i7fq6k87cd005qvlzk1ys1aj08hsrq9dmzx";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "profunctor" = pkgs.stdenv.mkDerivation {
        name = "profunctor";
        version = "78b2577b62fcbd0aa9232aac214faa8dab378096";
        src = pkgs.fetchgit {
          url = "https://github.com/purenix-org/purescript-profunctor.git";
          rev = "78b2577b62fcbd0aa9232aac214faa8dab378096";
          sha256 = "1i3hgncwb7kcfaaxwz27d41qcjazcwqibgg71l3mfcl7cbrgffx8";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "safe-coerce" = pkgs.stdenv.mkDerivation {
        name = "safe-coerce";
        version = "048f4e64210d93cc0515f3ea236d38aad9787914";
        src = pkgs.fetchgit {
          url = "https://github.com/purenix-org/purescript-safe-coerce.git";
          rev = "048f4e64210d93cc0515f3ea236d38aad9787914";
          sha256 = "1041fbdmm5a3wswmw24bg5h5x2ifs8wl4zj95cp1m42cv5zbv1yg";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "st" = pkgs.stdenv.mkDerivation {
        name = "st";
        version = "cfdcc169101bd3188747051d0886e33615ab7c2c";
        src = pkgs.fetchgit {
          url = "https://github.com/purenix-org/purescript-st.git";
          rev = "cfdcc169101bd3188747051d0886e33615ab7c2c";
          sha256 = "1nvbdr30j84jy3qv4l6a7s7z4nv20v5ycqi1qc65idlj74807yv5";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "tuples" = pkgs.stdenv.mkDerivation {
        name = "tuples";
        version = "1ea47bb6ff4f5aa04a42ca01c3a78bca48160743";
        src = pkgs.fetchgit {
          url = "https://github.com/purenix-org/purescript-tuples.git";
          rev = "1ea47bb6ff4f5aa04a42ca01c3a78bca48160743";
          sha256 = "0mxnrhlp12ddkb40wqb7bv65nhf7ldanxd65nw2wp5xykc90gwwn";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "type-equality" = pkgs.stdenv.mkDerivation {
        name = "type-equality";
        version = "f251a957aa464013d625d37aaaa430e16dee8f21";
        src = pkgs.fetchgit {
          url = "https://github.com/purenix-org/purescript-type-equality.git";
          rev = "f251a957aa464013d625d37aaaa430e16dee8f21";
          sha256 = "1zm4yaiiwzg66zfd74jrn7lf4mq4w56jgz0gf7x454zfx0vjxiy1";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "unfoldable" = pkgs.stdenv.mkDerivation {
        name = "unfoldable";
        version = "3466c8e7d5554040f034ec792124e3271ea46e57";
        src = pkgs.fetchgit {
          url = "https://github.com/purenix-org/purescript-unfoldable.git";
          rev = "3466c8e7d5554040f034ec792124e3271ea46e57";
          sha256 = "11kkinb3v23n1il6iwnv21ap9fxyavngakhjj84254nwgnvlnpzl";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

    "unsafe-coerce" = pkgs.stdenv.mkDerivation {
        name = "unsafe-coerce";
        version = "dba4c8cfc6b09e09f172fbeac04697724b015b02";
        src = pkgs.fetchgit {
          url = "https://github.com/purenix-org/purescript-unsafe-coerce.git";
          rev = "dba4c8cfc6b09e09f172fbeac04697724b015b02";
          sha256 = "1772589069vpnr84p9vrk38adj9wycm7w42g7pll75d8y3rn310v";
        };
        phases = "installPhase";
        installPhase = "ln -s $src $out";
      };

  };

  cpPackage = pkg:
    let
      target = ".spago/${pkg.name}/${pkg.version}";
    in ''
      if [ ! -e ${target} ]; then
        echo "Installing ${target}."
        mkdir -p ${target}
        cp --no-preserve=mode,ownership,timestamp -r ${toString pkg.outPath}/* ${target}
      else
        echo "${target} already exists. Skipping."
      fi
    '';

  getGlob = pkg: ''".spago/${pkg.name}/${pkg.version}/src/**/*.purs"'';

  getStoreGlob = pkg: ''"${pkg.outPath}/src/**/*.purs"'';

in {
  inherit inputs;

  installSpagoStyle = pkgs.writeShellScriptBin "install-spago-style" ''
      set -e
      echo installing dependencies...
      ${builtins.toString (builtins.map cpPackage (builtins.attrValues inputs))}
      echo "echo done."
  '';

  buildSpagoStyle = pkgs.writeShellScriptBin "build-spago-style" ''
      set -e
      echo building project...
      purs compile ${builtins.toString (builtins.map getGlob (builtins.attrValues inputs))} "$@"
      echo done.
  '';

  buildFromNixStore = pkgs.writeShellScriptBin "build-from-store" ''
      set -e
      echo building project using sources from nix store...
      purs compile ${builtins.toString (
        builtins.map getStoreGlob (builtins.attrValues inputs))} "$@"
      echo done.
  '';

  mkBuildProjectOutput =
    { src, purs }:

    pkgs.stdenv.mkDerivation {
      name = "build-project-output";
      src = src;

      buildInputs = [ purs ];

      installPhase = ''
        mkdir -p $out
        purs compile "$src/**/*.purs" ${builtins.toString
          (builtins.map
            (x: ''"${x.outPath}/src/**/*.purs"'')
            (builtins.attrValues inputs))}
        mv output $out
      '';
    };
}
