name: "CI"
on:
  pull_request:
  push:
jobs:
  tests:
    env:
      NIX_PATH: "nipkgs=https://github.com/NixOS/nixpkgs/archive/8588b14a397e045692d0a87192810b6dddf53003.tar.gz"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix develop --command spago docs

      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: generated-docs/html
