name: "CI"
on:
  pull_request:
  push:
jobs:
  checks:
    env:
      NIX_PATH: "nipkgs=https://github.com/NixOS/nixpkgs/archive/8588b14a397e045692d0a87192810b6dddf53003.tar.gz"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Install Nix
        uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Check shell
        run: nix develop --command echo 123

      - name: Cabal update
        run: nix develop --command cabal update

      - name: Check Tasks.hs
        run: nix develop --command ./run --help

      - name: CI
        run: nix develop --command ./run -d ci

  deploy:
    - name: Deploy Docs to GH Pages
      if: github.ref == 'refs/heads/main'
      needs: checks
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: dist
